name: NotifyWebhookOnPRToDevelop

on:
  pull_request:
    branches:
      - develop

jobs:
  sendWebhookNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_type: json
          INPUT_DATA: '{"event": "pull_request_created", "repository": "${{ github.repository }}", "commit": "${{ github.sha }}", "ref": "${{ github.ref }}"}'
